import React from 'react'

export default function Studentlar() {
  return (
    <div>
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Itaque quae nemo quam blanditiis. Distinctio, sequi! Tempora sequi corporis autem deleniti itaque hic distinctio placeat perferendis exercitationem modi labore illum eveniet similique consectetur saepe veniam nesciunt dolorem in pariatur aut ducimus, nostrum sunt. Commodi tempore voluptatum neque eligendi rerum vitae animi nihil amet! Fugiat deleniti esse quo, magni ut aut minima deserunt odio ratione dolor itaque quasi consequatur totam impedit necessitatibus blanditiis alias quam ullam exercitationem aliquid, pariatur a iure debitis asperiores. Quo doloremque a tempora excepturi, culpa commodi iste eos ipsum. Odit, magnam est quia aperiam odio tempora quam hic error ex modi atque explicabo quod excepturi corrupti doloremque quaerat saepe molestias sapiente quidem magni labore mollitia blanditiis incidunt nostrum? Soluta, architecto! Nulla sapiente, corrupti soluta, reprehenderit doloremque dolores nam molestias eos recusandae iure labore incidunt pariatur consequatur omnis illo quis quisquam ratione a laboriosam voluptas quia. Itaque, possimus? Praesentium repellat voluptatem dignissimos voluptas! Fugit cum odit quos. Labore omnis velit assumenda dignissimos incidunt provident numquam ducimus voluptate commodi? Ab autem, voluptates labore voluptatibus vero quisquam consectetur temporibus laboriosam nulla repellat explicabo eaque modi, eveniet iure corrupti, quae natus. Fugit minima itaque iste dolores quis, praesentium assumenda, voluptates provident architecto eligendi laborum facere, non eius suscipit voluptatum aspernatur repudiandae velit excepturi consequatur modi exercitationem delectus doloremque! Pariatur mollitia eveniet neque maiores accusamus molestiae fuga cupiditate beatae deleniti corrupti hic adipisci architecto quo ipsa, magnam deserunt laboriosam ex modi rem dolorum iure cum repellat aliquid. Id aut nobis saepe cupiditate tenetur, minus quis vitae eos labore ipsum ipsam sit officia natus perferendis blanditiis dicta repellat! Sequi nobis itaque saepe odio libero dicta, ullam, sapiente similique quas dolorum ipsa incidunt, ex laborum reiciendis quod sit expedita soluta esse debitis aut beatae! At assumenda deserunt cupiditate laborum expedita tempore sunt ducimus aliquid repellendus corrupti tenetur, iure necessitatibus tempora in quis impedit atque modi cumque iste itaque quia ipsa! Quod, natus corrupti quos qui, repudiandae quae voluptates labore accusantium alias, facere voluptatum sapiente voluptas animi nostrum provident!
    </div>
  )
}
